### ISSUE TITLE
Can't read font interface

### ISSUE THREAD

**Issue by HourSokaonKH** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#49] opened 2022-06-23 14:23 UTC
Got this strange font when loaded the application
![Screenshot 2022-06-23 212056](https://user-images.githubusercontent.com/67731386/175322347-7785b41f-c18d-48fe-b09d-c189f1b34708.jpg)

**Comment by ahmedayman4a** [comment] 2022-08-03 10:04
Duplicate of #42. Here is my response to this issue:
Can you try uninstalling the quicksand font from your computer and rerunning the app. Don't worry, you can reinstall it easily.
A font file could also be corrupt. Could you try uninstalling the app then redownloading the app from [here](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/releases) and installing it.

**Closed as completed** 2022-08-13 11:20 UTC
