### ISSUE TITLE
LEARNING PATH DOWNLOADER

### ISSUE THREAD

**Issue by rd0769** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#36] opened 2022-03-05 22:47 UTC
**Is your feature request related to a problem? Please describe.**
There is a learning path feature in linkedIN learning, which includes set of 2 or more courses, when you do all coursef them you are certified for that post e.g " AGILE PROJECT MANAGER".

**Describe the solution you'd like**
CAN GET CODE FROM HERE - https://github.com/lawrensylvan/linkedin-learning-courses-downloader

**Describe alternatives you've considered**
Individially downloading each course or pasting links of Individial or multiple courses

**Additional context**
"https://www.linkedin.com/learning/paths/become-an-agile-project-manager"

![image](https://user-images.githubusercontent.com/39245627/156902189-5dee9542-8b3d-479a-ad9c-65b5701e5d00.png)
![image](https://user-images.githubusercontent.com/39245627/156902204-e623f0ba-164f-4f22-9235-a9ea732521f4.png)

**Comment by pcpepik** [comment] 2022-03-22 22:14
I believe this is a duplicate of #30

**Closed as completed** 2022-03-24 09:36 UTC
Labels: duplicate, enhancement
