### ISSUE TITLE
Non english words in version 1.2 [BUG]

### ISSUE THREAD

**Issue by roykamsi** [ahmedayman4a/Linkedin-Learning-Courses-Downloader#45] opened 2022-05-25 10:44 UTC
The words in the 1.2 version of the software aren't in English and the input as well. Hence the software is unusable, but the 1.1 version seems more stable and I was able to download the whole course. The software you made is fantastic Ahmed!

![image](https://user-images.githubusercontent.com/59699671/170244494-2362b8ac-6109-4101-a05e-433f8515eeb0.png)

**Windows Version**
Windows 10 Pro 20H2

**Log File**

2022-05-25 12:42:23.149 +02:00 [INF] Setting key value for icon in registry
2022-05-25 12:42:23.170 +02:00 [INF] Current exe path : C:/Users/Michele Antonio/AppData/Local/Linkedin-Learning-Courses-Downloader/app-1.2.0/Linkedin-Learning-Courses-Downloader.exe
2022-05-25 12:42:23.170 +02:00 [INF] Key value for icon is set successfully
2022-05-25 12:42:23.171 +02:00 [INF] Restoring config file
2022-05-25 12:42:23.171 +02:00 [INF] No config file to restore is found
2022-05-25 12:42:23.546 +02:00 [INF] No Config is found
2022-05-25 12:42:23.942 +02:00 [INF] Checking for updates...
2022-05-25 12:42:24.586 +02:00 [INF] No updates detected.
2022-05-25 12:43:50.854 +02:00 [ERR] Cookies not found at "Default\Network\Cookies". Trying "Default\Cookies"
code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   in System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   in System.Data.SQLite.SQLiteConnection.Open()
   in LLCD.CourseExtractor.CookiesExtractor.GetChromeCookiesFromDB(String dbPath, Byte[] decodedKey)
   in LLCD.CourseExtractor.CookiesExtractor.ReadChromiumCookies(String profilePath)
2022-05-25 12:44:37.488 +02:00 [INF] Validating Input
2022-05-25 12:44:40.168 +02:00 [INF] Input Invalid

**Comment by ahmedayman4a** [comment] 2022-05-25 15:43
Duplicate of #42. Here is my response to this issue:
Can you try uninstalling the quicksand font from your computer and rerunning the app. Don't worry, you can reinstall it easily.
A font file could also be corrupt. Could you try uninstalling the app then redownloading the app from [here](https://github.com/ahmedayman4a/Linkedin-Learning-Courses-Downloader/releases) and installing it.

**Comment by CombTech** [comment] 2022-06-10 00:41
In the meantime for V1.2 you could always use the image on the code page for guidance. Thats what I did and all worked well
![Linkedin-Learning-Downloader-Screenshot](https://user-images.githubusercontent.com/75885655/172967831-6719d5fb-d1d1-4c14-b4a5-e884c0ffd39f.png)
.

**Comment by roykamsi** [comment] 2022-06-10 08:05
> In the meantime for V1.2 you could always use the image on the code page for guidance. Thats what I did and all worked well ![Linkedin-Learning-Downloader-Screenshot](https://user-images.githubusercontent.com/75885655/172967831-6719d5fb-d1d1-4c14-b4a5-e884c0ffd39f.png) .

The problem was the font @ahmedayman4a pointed at (Quicksand), thanks! Without that, I couldn't even type because the font itself was 'corrupted' as @ahmedayman4a said. So for example if I inserted an 'abc' sequence it could have became 'k%à' (so non-sense).

**Closed as completed** 2022-06-10 08:05 UTC
Labels: bug
